#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 yi-mediad contributors
"""Generate the 8x16 1bpp ASCII font used by osd.c.

Renders ASCII 32..126 from a monospace TTF into 8x16 cells and emits a C header
(one glyph = 16 bytes, MSB = leftmost pixel). Run once; the output is committed
as osd_font.h (no runtime/build dependency on the TTF).

  python3 tools/gen_osd_font.py <ttf> -o osd_font.h
"""
import sys, argparse
from PIL import Image, ImageDraw, ImageFont

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ttf")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--size", type=int, default=14)
    ap.add_argument("--cell", type=int, default=16)
    ap.add_argument("--glyph-w", type=int, default=8)
    a = ap.parse_args()

    f = ImageFont.truetype(a.ttf, a.size)
    rows = []
    for code in range(32, 127):
        img = Image.new("L", (a.glyph_w, a.cell), 0)
        d = ImageDraw.Draw(img)
        ch = chr(code)
        bb = d.textbbox((0, 0), ch, font=f)
        x = (a.glyph_w - (bb[2] - bb[0])) // 2 - bb[0]
        y = (a.cell - (bb[3] - bb[1])) // 2 - bb[1]
        d.text((x, y), ch, fill=255, font=f)
        line = []
        for r in range(a.cell):
            b = 0
            for c in range(a.glyph_w):
                if img.getpixel((c, r)) > 127:
                    b |= 0x80 >> c
            line.append(b)
        rows.append(line)

    with open(a.out, "w") as fp:
        fp.write("// SPDX-License-Identifier: AGPL-3.0-only\n"
                 "// Copyright (C) 2026 yi-mediad contributors\n"
                 "/* GENERATED by tools/gen_osd_font.py - 8x%d 1bpp ASCII 32..126.\n"
                 " * Source font: %s. MSB = leftmost pixel. Do not edit. */\n"
                 % (a.cell, a.ttf.split('/')[-1]))
        fp.write("#ifndef MEDIAD_OSD_FONT_H\n#define MEDIAD_OSD_FONT_H\n\n")
        fp.write("#define OSD_FONT_W %d\n#define OSD_FONT_H %d\n#define OSD_FONT_FIRST 32\n#define OSD_FONT_LAST 126\n\n"
                 % (a.glyph_w, a.cell))
        fp.write("static const unsigned char osd_font[%d][%d] = {\n" % (len(rows), a.cell))
        for i, line in enumerate(rows):
            fp.write("    { %s }, /* %d %r */\n" % (", ".join("0x%02x" % b for b in line), 32+i, chr(32+i)))
        fp.write("};\n\n#endif\n")
    print("wrote %s (%d glyphs, %dx%d)" % (a.out, len(rows), a.glyph_w, a.cell))

if __name__ == "__main__":
    main()
