#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 yi-mediad contributors
"""
gen_rmm_layout.py - emit the stock-521 -> V833 struct remap used by rmm_tuning.c.

There is no per-firmware data here: the only thing compiled in is the byte-copy
tuple list that translates stock rmm's isp_param_config sections into our V833
tree's layout, in the enum ABI of the build. rmm_tuning.c finds the sections
itself at runtime by scanning the camera's own /home/app/rmm for the sensor
name and following its config pointers - no addresses are hardcoded.

  --abi short|long  select the target enum ABI (ALGO_RTOS=1 uses -fshort-enums)
  -o <header>       write the C header

The section sizes/layout come from extract_isp_cfg (isp_layout_521), the
single source for the recovered 521 layout; no vendor bytes are involved.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import extract_isp_cfg as E

TEST = "isp_test_param"
A3 = "isp_3a_param"
TUN = "isp_tunning_param"
DYN = "isp_dynamic_param"

# destination (= our V833 tree struct) section bases
TEST_BASE = 0
A3_BASE = E.SIZES_521[TEST]                         # 216
TUN_BASE = A3_BASE + E.SIZES_521[A3]                # 6052
DYN_BASE = TUN_BASE + E.SIZES_521[TUN]              # 124648
# tunning layout fix offsets (see extract_isp_cfg.fix_tunning_v833)
GCA = E.V833_TUNNING_GCA_OFF                        # 87144
GCA_DST = E.V833_TUNNING_GCA_SIZE                   # 28
GCA_SRC = E.STOCK_TUNNING_GCA_SIZE                  # 36
# dynamic enum ABI (see extract_isp_cfg / rmm_tuning.c)
DYN_LONG = 8468
DYN_SHORT = 8420
TRIGER_N = 17


def remap_tuples(abi):
    """(section, dst_off, src_off_within_section, len) for the 521 stock layout
    -> our V833 struct. ABI-independent except the dynamic trigger enum size."""
    t = [(0, TEST_BASE, 0, E.SIZES_521[TEST]),
         (1, A3_BASE, 0, E.SIZES_521[A3]),
         # tunning: prefix identity, gca_cfg skips the two isp522-only leading
         # entries, then everything shifts down by 8
         (2, TUN_BASE + 0, 0, GCA),
         (2, TUN_BASE + GCA, GCA + GCA_SRC - GCA_DST, GCA_DST),
         (2, TUN_BASE + GCA + GCA_DST, GCA + GCA_SRC, E.SIZES_521[TUN] - (GCA + GCA_SRC))]
    if abi == "long":
        t.append((3, DYN_BASE, 0, DYN_LONG))
    else:
        for i in range(TRIGER_N):                   # 17 enums, 4B -> 1B
            t.append((3, DYN_BASE + i, 4 * i, 1))
        t.append((3, DYN_BASE + 20, 68, 56))        # lum mapping points
        t.append((3, DYN_BASE + 76, 124, 56))       # gain mapping points
        t.append((3, DYN_BASE + 132, 180, DYN_LONG - 180))
    return t


def blob_size(abi):
    return DYN_BASE + (DYN_LONG if abi == "long" else DYN_SHORT)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--abi", choices=("short", "long"), required=True)
    ap.add_argument("-o", "--out", required=True)
    a = ap.parse_args()

    with open(a.out, "w") as f:
        f.write("/* GENERATED by tools/gen_rmm_layout.py - stock-521 -> V833\n"
                " * isp_param_config section remap. No vendor bytes. do not edit. */\n")
        f.write("#ifndef RMM_LAYOUT_H\n#define RMM_LAYOUT_H\n\n")
        f.write("#define RMM_BLOB_SIZE %du\n#define RMM_ABI_%s 1\n\n"
                % (blob_size(a.abi), a.abi.upper()))
        f.write("typedef struct { unsigned char sect; unsigned int dst, src,"
                " len; } rmm_copy_t;\n")
        f.write("static const rmm_copy_t rmm_remap[] = {\n")
        for sect, dst, src, ln in remap_tuples(a.abi):
            f.write("    {%d, %du, %du, %du},\n" % (sect, dst, src, ln))
        f.write("};\n#define RMM_REMAP_N %d\n\n" % len(remap_tuples(a.abi)))
        f.write("#endif\n")
    print("wrote %s (abi=%s, %d tuples)" % (a.out, a.abi, len(remap_tuples(a.abi))))


if __name__ == "__main__":
    main()
