#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 yi-mediad contributors

# Generate osd_font.h from 8x16 and 16x32 BDF fonts, glyphs copied unmodified,
# keeping the font's copyright/licence header with the output:
#   python3 tools/gen_osd_font_bdf.py ter-u16b.bdf ter-u32b.bdf -o osd_font.h
import argparse


def load(path, w, h):
    glyphs, enc, rows, inbm, bbx, copyright = {}, None, [], False, None, ''
    for line in open(path, encoding='latin-1'):
        t = line.split()
        if not t:
            continue
        if t[0] == 'COPYRIGHT':
            copyright = line.split(None, 1)[1].strip().strip('"')
        elif t[0] == 'ENCODING':
            enc = int(t[1])
        elif t[0] == 'BBX':
            bbx = tuple(int(v) for v in t[1:3])
        elif t[0] == 'BITMAP':
            inbm, rows = True, []
        elif t[0] == 'ENDCHAR':
            inbm = False
            if enc is not None and 32 <= enc <= 126:
                if bbx != (w, h) or len(rows) != h:
                    raise SystemExit('%s: glyph %d is not a full %dx%d cell' % (path, enc, w, h))
                glyphs[enc] = rows
        elif inbm:
            rows.append(int(t[0], 16))
    missing = [c for c in range(32, 127) if c not in glyphs]
    if missing:
        raise SystemExit('%s: missing glyphs %s' % (path, missing))
    return glyphs, copyright


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('bdf8x16')
    ap.add_argument('bdf16x32')
    ap.add_argument('-o', '--out', required=True)
    a = ap.parse_args()
    s1, c1 = load(a.bdf8x16, 8, 16)
    s2, c2 = load(a.bdf16x32, 16, 32)
    o = []
    o.append('/* SPDX-License-Identifier: OFL-1.1 */')
    o.append('/* GENERATED by tools/gen_osd_font_bdf.py - do not edit.')
    o.append(' *')
    o.append(' * Glyph bitmaps (ASCII 32..126, unmodified) from the Terminus bitmap font,')
    o.append(' * bold weight, 8x16 (ter-u16b) and 16x32 (ter-u32b), version 4.49.1.')
    o.append(' * %s.' % (c1 or c2))
    o.append(' * Licensed under the SIL Open Font License 1.1: see fonts/OFL-Terminus.txt,')
    o.append(' * which must be distributed with this file.  MSB = leftmost pixel.')
    o.append(' */')
    o.append('#ifndef MEDIAD_OSD_FONT_H')
    o.append('#define MEDIAD_OSD_FONT_H')
    o.append('')
    o.append('#define OSD_FONT_W 8      /* base cell; the 2x table is exactly 2W x 2H */')
    o.append('#define OSD_FONT_H 16')
    o.append('#define OSD_FONT_FIRST 32')
    o.append('#define OSD_FONT_LAST 126')
    o.append('')
    o.append('static const unsigned char osd_font[95][16] = {')
    for c in range(32, 127):
        o.append('    { %s }, /* %d %r */' % (', '.join('0x%02x' % r for r in s1[c]), c, chr(c)))
    o.append('};')
    o.append('')
    o.append('static const unsigned short osd_font2x[95][32] = {')
    for c in range(32, 127):
        o.append('    { %s }, /* %d %r */' % (', '.join('0x%04x' % r for r in s2[c]), c, chr(c)))
    o.append('};')
    o.append('')
    o.append('#endif')
    open(a.out, 'w').write('\n'.join(o) + '\n')


if __name__ == '__main__':
    main()
